services:
  mysql_db:
    container_name: mysql_db
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_users
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  postgres_db:
    container_name: postgres_db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: msvc_courses
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  msvc-users:
    container_name: msvc-users
    build:
      context: .
      dockerfile: ./msvc-users/Dockerfile
    image: micro-users:0.0.1
    ports:
      - "8001:8001"
    env_file: ./msvc-users/.env
    depends_on:
      - mysql_db
    restart: always
  msvc-courses:
    container_name: msvc-courses
    build:
      context: .
      dockerfile: ./msvc-courses/Dockerfile
    image: micro-courses:0.0.1
    ports:
      - "8002:8002"
    env_file:
      - msvc-courses/.env
    depends_on:
      - postgres_db
    restart: always
volumes:
  mysql-data:
    name: mysql-data
  postgres-data:
    name: postgres-data